name: on_audio_query_android
description: Android implementation of the on_audio_query plugin.
version: 1.1.0
homepage: https://github.com/LucJosin/on_audio_query/tree/main/packages/on_audio_query_android

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  # platform interface for method channel communication
  on_audio_query_platform_interface: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    implements: on_audio_query
    platforms:
      android:
        package: com.lucasjosino.on_audio_query
        pluginClass: OnAudioQueryPlugin
